GET http://localhost:3002/api/persons/ HTTP/1.1

###
GET http://localhost:3002/info/ HTTP/1.1

###
GET http://localhost:3002/api/persons/68c9ace8a9d0e47d124a4f99 HTTP/1.1

###
POST http://localhost:3002/api/persons/ HTTP/1.1
Content-Type: application/json

{
  "name": "lion",
  "number": "09-1234556"
}

###
POST http://localhost:3002/api/persons/ HTTP/1.1
Content-Type: application/json

{
  "name": "Panda",
  "number": "987-654"
}

###
PUT http://localhost:3002/api/persons/68d97cbe2cede15dff4af5a8 HTTP/1.1
Content-Type: application/json

{
  "number": "456"
}

###
PUT http://localhost:3002/api/persons/68da98dc6e6aeb35841abb79 HTTP/1.1
Content-Type: application/json

{
  "name": "k"
}